CREATE DATABASE prueba3;
USE prueba3;

CREATE TABLE Usuarios (
    ID INT PRIMARY KEY AUTO_INCREMENT,
    Apellido VARCHAR(50) NOT NULL,
    Nombre VARCHAR(50) NOT NULL,
    Correo VARCHAR(50) NOT NULL UNIQUE,
    Contrasena VARCHAR(255) NOT NULL,
    Telefono VARCHAR(10) NOT NULL,
    Rol TINYINT(1) NOT NULL DEFAULT 0, -- 0 = normal, 1 = admin
    CONSTRAINT chk_Correo_Extension CHECK (Correo LIKE '%@%')
);

CREATE TABLE Reseñas (
    ID INT AUTO_INCREMENT PRIMARY KEY,
    UsuarioID INT NOT NULL,
    Reseña TEXT NOT NULL,
    Fecha TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (UsuarioID) REFERENCES Usuarios(ID) ON DELETE CASCADE
);